# Generated by Django 3.2.4 on 2021-07-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=40)),
                ('prezime', models.CharField(max_length=40)),
                ('korisnicko_ime', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('is_admin', models.BooleanField(default=0)),
                ('aktivnost', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
