# Generated by Django 3.2.4 on 2021-09-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0002_auto_20210714_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='korisnik',
            name='tip_korisnika',
            field=models.CharField(default='', max_length=70),
        ),
    ]
