# Generated by Django 3.2.4 on 2021-09-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0003_auto_20210912_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='aktivnost',
            field=models.CharField(default='aktivan', max_length=70),
        ),
    ]
