# Generated by Django 3.2.4 on 2021-09-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0004_alter_korisnik_aktivnost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('termin_predavanja', models.TimeField()),
                ('termin_vjezbi', models.TimeField()),
                ('datum_odrzavanja', models.DateField()),
                ('godina', models.IntegerField()),
                ('semestar', models.IntegerField()),
                ('asistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistent', to='aplikacija.korisnik')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to='aplikacija.korisnik')),
            ],
        ),
    ]
