# Generated by Django 3.2.4 on 2021-09-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0005_predmet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predmet',
            name='datum_odrzavanja',
        ),
    ]
