# Generated by Django 3.2.4 on 2021-09-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0006_remove_predmet_datum_odrzavanja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='termin_predavanja',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='termin_vjezbi',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
