# Generated by Django 3.2.4 on 2021-09-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0007_auto_20210913_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='termin_predavanja',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='termin_vjezbi',
            field=models.TimeField(),
        ),
    ]
